### PR TITLE
replace empty value form option for placeholder

### PR DESCRIPTION
**Pull request by almacbe**
Solve #14 and we do compatible this bundle with symfomy 3

### CODE REVIEW

**Comment by MauroCasula** [comment]
Thanks @almacbe! Please @Gladhon merge this! :)

**Comment by Gladhon** [comment]
@MauroCasula @almacbe looks good for me, but i'm not able to merge
perhaps @vstm  can merge it?

**Comment by tillackt** [comment]
Thanks for the PR! Please merge this...

**Comment by almacbe** [comment]
@vstm ping

**Pull request merged**
