### PR TITLE
Added ability to filter for non translated keys and languages

### PR DESCRIPTION
**Pull request by mikelohmann**
We have the need to filter for non translated keys and languages.
By that I only changed the way the files are received to get the domain names out of it.

### CODE REVIEW

**Comment by Gladhon** [comment]
Thx for request. 
I've seen you try to find auch non-translated key's. To do that, you work with prefixes, but how come these prefixes in your DB ?

Why you change the way to get domain-names?

**Comment by mikelohmann** [comment]
Hi,

I used the inbuilt app/console translation:update command to update the message files locally.  It takes a parameter —prefix to indicate non existing values for keys in one language.
This is new_ per default. So I thought it would be a good idea to make it configurable in case to search for empty values.

I changed the way, because we have man files in our project to translate and is a litte bit faster not to fetch and hydrate all objects if just a specific field is needed.

Regards.

Mike

**Comment by Gladhon** [comment]
I've merged it, but i have changed the filter for non existing a bit. Now it uses left-joins and locales, so you can search for missed translation-records for specific locales.

Theres also a little problem with your default "new_". The underline will be interpreted as single wildcard, so texts like "new Password" will also shown as not translated. Perhaps it could be solved by adding an backspace, what do you think?

**Comment by mikelohmann** [comment]
Hi,

I think this is a good approach. I will change that.
Thanks your addition regarding filtering.

Mike

**Comment by Gladhon** [comment]
@mikelohmann  
Why did you add your own entities instead using default lexik entities

**Pull request merged**
